import { lexendDeca, righteous } from '@/lib/fonts'
import { Providers } from '@/redux/Providers'

import './globals.css'

export const metadata = {
  title: 'V3 Bordeaux',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className={`${lexendDeca.variable} ${righteous.variable} font-sans bg-background-3 text-text-1`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
